# Generated by Django 4.2 on 2023-04-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('DOB', models.DateField()),
                ('Phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('ZipCode', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Image', models.CharField(max_length=255)),
            ],
        ),
    ]
